api/urls.py
from django.urls import path
from .views import CategoryList, CategoryDetail, ThemePostList, PostList, PostDetail, TagDetail, TagList


app_name = 'api'

urlpatterns = [
    path('categories', CategoryList.as_view()),
    path('categories/<int:pk>', CategoryDetail.as_view()),
    path('themes/<str:theme_slug_name>/posts', ThemePostList.as_view()),
    path('posts', PostList.as_view()),
    path('posts/<int:pk>', PostDetail.as_view()),
    path('tags', TagList.as_view()),
    path('tags/<int:pk>', TagDetail.as_view()),
]

blog/urls.py
from django.urls import register_converter, path
from .views import BlogCreateView, MemberBlogPostDetailView,  MemberBlogView, upload
from .views import MemberBlogSettingView, MemberBlogSettingPostCreateView, MemberBlogSettingPostListView, MemberBlogSettingPostEditView
from .views import MemberBlogSettingCategoryListView, MemberBlogSettingTagListView, MemberBlogSettingUserView
from . import converters

app_name = 'blog'

# url 한글 slug 문제 해결
register_converter(converters.UnicodeSlugConverter, 'uslug')

urlpatterns = [
    path('add', BlogCreateView.as_view(), name='add'),
    path('upload', upload, name='upload'),
    path('<str:username>/settings/categories', MemberBlogSettingCategoryListView.as_view(), name='member_blog_setting_category'),
    path('<str:username>/settings/posts/<int:pk>', MemberBlogSettingPostEditView.as_view(), name='member_blog_setting_post_edit'),
    path('<str:username>/settings/posts/new', MemberBlogSettingPostCreateView.as_view(), name='member_blog_setting_post_new'),
    path('<str:username>/settings/posts', MemberBlogSettingPostListView.as_view(), name='member_blog_setting_post'),
    path('<str:username>/settings/tags', MemberBlogSettingTagListView.as_view(), name='member_blog_setting_tag'),
    path('<str:username>/settings/user', MemberBlogSettingUserView.as_view(), name='member_blog_setting_user'),
    path('<str:username>/settings', MemberBlogSettingView.as_view(), name='member_blog_setting'),
    path('<str:username>/<uslug:slug_title>', MemberBlogPostDetailView.as_view(), name='member_blog_post_detail'),
    path('<str:username>', MemberBlogView.as_view(), name='member_blog'),
]

config/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from blog.views import BlogView
from .views import IndexView, JoinView

urlpatterns = [
    path('admin', admin.site.urls),
    path('api/', include('api.urls')),
    path('blog', BlogView.as_view(), name='blog_index'),
    path('blog/', include('blog.urls')),
    path('join', JoinView.as_view(), name='join'),
    path('login', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('password-reset', auth_views.PasswordResetView.as_view(template_name='password_reset.html', subject_template_name='password_reset_subject.txt', email_template_name='password_reset_email.html'), name='password_reset'),
    path('password-reset-complete', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-done', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('', IndexView.as_view(), name='index'),
]

blog/models.py
from django.db import models

#https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#referencing-the-user-model
from django.conf import settings


class Theme(models.Model):
    name = models.CharField(max_length=30, unique=True)
    slug_name = models.SlugField(max_length=50, unique=True, allow_unicode=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Blog(models.Model):
    name = models.CharField(max_length=50, unique=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    theme = models.ForeignKey(Theme, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=30)
    slug_name = models.SlugField(max_length=50, unique=True, allow_unicode=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

class Attachment(models.Model):
    name = models.CharField(max_length=30)
    image = models.ImageField(upload_to='blog/%Y/%m/%d')
    created_date = models.DateTimeField(auto_now_add=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=30)
    slug_name = models.SlugField(max_length=50, unique=True, allow_unicode=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    content = models.TextField()
    thumbnail = models.ImageField(upload_to='blog/%Y/%m/%d', blank=True) #upload path 문자열이 저장됨.
    slug_title = models.SlugField(max_length=150, unique=True, allow_unicode=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    tag = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from .models import Attachment, Blog, Category, Post, Tag


class BlogCreateForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['name', 'theme']

class MemberBlogSettingPostCreateAndEditForm(forms.ModelForm):
    form_tags = {'title': '제목', 'thumbnail': '썸네일', 'category': '카테고리', 'tag': '태그', 'content': '내용'}
    tag = forms.CharField(max_length=100, required=False)
    content = forms.CharField(widget=forms.Textarea, required=False)

    class Meta:
        model = Post
        fields = ['title', 'thumbnail', 'category', 'tag', 'content']
    
    def __init__(self, blog, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for key, value in self.form_tags.items():
            self.fields[key].label = value
            self.fields[key].widget.attrs.update({'class': 'form-control'})

            if key == 'category':
                self.fields[key].queryset = Category.objects.filter(blog=blog)
            elif key == 'tag':
                self.fields[key].widget.attrs.update({'data-role': 'tagsinput'})

class UploadImageFileForm(forms.Form):
    image = forms.ImageField()

class CustomPasswordChangeForm(PasswordChangeForm):
    form_tags = {'old_password': '이전 비밀번호', 'new_password1': '새 비밀번호', 'new_password2': '새 비밀번호 확인'}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for key, value in self.form_tags.items():
            self.fields[key].label = value
            self.fields[key].widget.attrs.update({'class': 'form-control'})

blog/views.py
import uuid
from django.views import View
from django.views.generic import CreateView, DetailView, ListView, TemplateView, UpdateView
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Group, User
from django.contrib.auth.decorators import login_required, permission_required
from django.db import transaction
from django.db.models import Count, Q
from django.http import HttpResponse, Http404, JsonResponse
from django.utils.text import slugify
from .models import Attachment, Blog, Category, Theme, Post, Tag
from .forms import BlogCreateForm, CustomPasswordChangeForm, MemberBlogSettingPostCreateAndEditForm, UploadImageFileForm


class BlogView(ListView):
    model = Post
    paginate_by = 6
    template_name = 'blog/blog.html'

    def get_queryset(self):
        search_type = self.request.GET.get('search-type', '')
        value = self.request.GET.get('value', '')

        if search_type and value:
            if search_type == 'question':
                return Post.objects.filter(Q(title__icontains=value) | Q(content__icontains=value) | Q(blog__name__icontains=value) | Q(user__username__icontains=value)).order_by('-id')

        return Post.objects.none()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['theme_list'] = Theme.objects.all()
        search_type = self.request.GET.get('search-type', '')
        value = self.request.GET.get('value', '')

        if search_type and value:
            context['search_type'] = search_type
            context['value'] = value

        return context

class BlogCreateView(LoginRequiredMixin, PermissionRequiredMixin, View):
    form_class = BlogCreateForm
    login_url = '/login'
    permission_required = 'blog.add_blog'
    redirect_field_name = '/login'
    success_url = '/blog'

    def get(self, request, *args, **kwargs):
        return HttpResponse(status=404)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            with transaction.atomic():
                request_user = self.request.user
                new_blog = form.save(commit=False)
                new_blog.user = request_user
                new_blog.save()
                
                blogger_group = Group.objects.get(name='Blogger')
                blogger_group.user_set.add(request_user)
                
                member_group = Group.objects.get(name='Member')
                request_user.groups.remove(member_group)
                
                messages.success(self.request, '<strong>블로그 만들기에 성공했습니다!</strong> 이제 당신은 블로거가 되었습니다.')
        else:
            error_data = form.errors.get_json_data()
            
            if 'name' in error_data and error_data['name'][0]['code'] == 'unique':
                messages.error(self.request, '<strong>같은 이름의 블로그가 이미 존재합니다.</strong> 블로그 이름을 다른 이름으로 지으세요.')
        
        return redirect(self.success_url)

class MemberBlogView(ListView):
    model = Post
    paginate_by = 6
    template_name = 'blog/member_blog.html'

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs['username'])
        search_type = self.request.GET.get('search-type', '')
        value = self.request.GET.get('value', '')

        if search_type and value:
            if search_type == 'question':
                return Post.objects.filter(Q(title__icontains=value) | Q(content__icontains=value), user=user).order_by('-id')
            elif search_type == 'category':
                if value == 'etc':
                    return Post.objects.filter(user=user, category__isnull=True).order_by('-id')
                    
                return Post.objects.filter(user=user, category__slug_name=value).order_by('-id')
            elif search_type == 'tag':
                return Post.objects.filter(user=user, tag__slug_name=value).order_by('-id')

        return Post.objects.filter(user=user).order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = get_object_or_404(User, username=self.kwargs['username'])
        blog =  get_object_or_404(Blog, user=user)
        context['blog'] = blog
        context['categories'] = Category.objects.filter(blog=blog).annotate(Count('post'))
        context['category_etc_count'] = Post.objects.filter(blog=blog, category__isnull=True).count()
        context['tags'] = Tag.objects.filter(blog=blog)

        search_type = self.request.GET.get('search-type', '')
        value = self.request.GET.get('value', '')

        if search_type and value:
            context['search_type'] = search_type
            context['value'] = value

        return context

class MemberBlogPostDetailView(DetailView):
    model = Post
    slug_field = 'slug_title'
    slug_url_kwarg = 'slug_title'
    template_name = 'blog/member_blog_post_detail.html'

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs['username'])
        
        return Post.objects.filter(user=user)
        
class MemberBlogSettingView(TemplateView):
    template_name = 'blog/member_blog_setting.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        blog = get_owner_blog(self)
        context['blog'] = blog
        
        categories = Category.objects.filter(blog=blog).annotate(Count('post'))
        dict_categories = {}

        for category in categories:
            dict_categories[category.name] = str(category.post__count)

        context['categories'] = dict_categories
        
        return context

class MemberBlogSettingPostListView(ListView):
    model = Post
    paginate_by = 4
    template_name = 'blog/member_blog_setting_post.html'

    def get_queryset(self):
        blog = get_owner_blog(self)
        search_type = self.request.GET.get('search-type', '')
        value = self.request.GET.get('value', '')

        if search_type and value:
            if search_type == 'question':
                return Post.objects.filter(Q(title__icontains=value) | Q(content__icontains=value), blog=blog).order_by('-id')

        return Post.objects.filter(blog=blog).order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_type = self.request.GET.get('search-type', '')
        value = self.request.GET.get('value', '')

        if search_type and value:
            context['search_type'] = search_type
            context['value'] = value
    
        return context

class MemberBlogSettingPostCreateView(CreateView):
    template_name = 'blog/member_blog_setting_post_new.html'

    def get(self, request, *args, **kwargs):
        context = {'form': MemberBlogSettingPostCreateAndEditForm(get_owner_blog(self))}

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        blog = get_owner_blog(self)
        form = MemberBlogSettingPostCreateAndEditForm(blog, request.POST, request.FILES)

        if form.is_valid():
            with transaction.atomic():
                new_tags = get_new_tags(self, form.cleaned_data['tag'])
                form.cleaned_data['tag'] = new_tags

                new_post = form.save(commit=False)
                new_post.slug_title = get_permalink(new_post.title)
                new_post.blog = blog
                new_post.user = request.user

                if new_post.thumbnail:
                    new_post.thumbnail.name = get_extension_permalink(new_post.thumbnail.name)

                new_post.save()
                form.save_m2m()

                messages.success(request, '글을 생성했습니다.')

            return redirect('blog:member_blog_setting_post', request.user)
        else:
            form = MemberBlogSettingPostCreateAndEditForm(blog)
        
        return render(request, self.template_name, {'form': form})

class MemberBlogSettingPostEditView(UpdateView):
    template_name = 'blog/member_blog_setting_post_edit.html'

    def get(self, request, *args, **kwargs):
        post = Post.objects.get(id=self.kwargs['pk'])
        tags = [tag.name for tag in list(post.tag.all())]
        tag_text = ','.join(tags)

        initial_data = {'title': post.title, 'thumbnail':  post.thumbnail, 'category': post.category, 'tag':  tag_text, 'content': post.content}
        context = {'form': MemberBlogSettingPostCreateAndEditForm(get_owner_blog(self), initial=initial_data)}

        print(context)

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        blog = get_owner_blog(self)
        form = MemberBlogSettingPostCreateAndEditForm(blog, request.POST, request.FILES)

        if form.is_valid():
            with transaction.atomic():
                post = Post.objects.get(id=self.kwargs['pk'])
                form_tag = get_new_tags(self, form.cleaned_data['tag'])
                form_title = form.cleaned_data['title']

                post.thumbnail = form.cleaned_data['thumbnail']
                post.category = form.cleaned_data['category']
                post.content = form.cleaned_data['content']

                if post.title is not form_title:
                    post.title = form_title
                    post.slug_title = get_permalink(post.title)
                
                post.tag.set(form_tag)
                post.save()

                messages.success(request, '글을 수정했습니다.')

            return redirect('blog:member_blog_setting_post', request.user)
        else:
            form = MemberBlogSettingPostCreateAndEditForm(blog)
        
        return render(request, self.template_name, {'form': form})

blog/templates/member_blog_setting_base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-161725487-1"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    
    gtag('config', 'UA-161725487-1');
    </script>
    
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    {% load static %}

    <!-- favicon -->
    <link rel="icon" href="{% static 'img/icon/favicon.ico' %}">

    <!-- Title Page-->
    <title>{{user.get_username}} 블로그 설정</title>

    <!-- Fontfaces CSS-->
    <link href="{% static 'cooladmin/css/font-face.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'cooladmin/vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'cooladmin/vendor/font-awesome-5/css/fontawesome-all.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'cooladmin/vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="{% static 'cooladmin/vendor/bootstrap-4.1/bootstrap.min.css' %}" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="{% static 'cooladmin/vendor/animsition/animsition.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'cooladmin/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'cooladmin/vendor/wow/animate.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'cooladmin/vendor/css-hamburgers/hamburgers.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'cooladmin/vendor/slick/slick.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'cooladmin/vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'cooladmin/vendor/perfect-scrollbar/perfect-scrollbar.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'cooladmin/css/theme.css' %}" rel="stylesheet" media="all">

    <!-- TagEditor CSS -->
    <link href="{% static 'cooladmin/tagEditor/jquery.tag-editor.css' %}" rel="stylesheet" media="all">

    <!-- TinyMCE JS -->
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
</head>

<body class="animsition">
    <div class="page-wrapper">
        <!-- HEADER MOBILE-->
        <header class="header-mobile d-block d-lg-none">
            <div class="header-mobile__bar">
                <div class="container-fluid">
                    <div class="header-mobile-inner">
                        <a href="/"><img src="{% static 'img/icon/for-creator-logo2.png' %}" alt="For-Creator-logo2"></a>
                        <button class="hamburger hamburger--slider" type="button">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
            <nav class="navbar-mobile">
                <div class="container-fluid">
                    <ul class="navbar-mobile__list list-unstyled">
                        <li>
                            <a href="{% url 'blog:member_blog_setting' user.get_username %}">
                                <i class="fas fa-home"></i>홈</a>
                        </li>
                        <li>
                            <a href="{% url 'blog:member_blog_setting_post' user.get_username %}">
                                <i class="fas fa-pencil-square-o"></i>글</a>
                        </li>
                        <li>
                            <a href="{% url 'blog:member_blog_setting_category' user.get_username %}">
                                <i class="fas fa-archive"></i>카테고리</a>
                        </li>
                        <li>
                            <a href="{% url 'blog:member_blog_setting_tag' user.get_username %}">
                                <i class="fas fa-tag"></i>태그</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- END HEADER MOBILE-->

        <!-- MENU SIDEBAR-->
        <aside class="menu-sidebar d-none d-lg-block">
            <div class="logo">
                <a href="/"><img src="{% static 'img/icon/for-creator-logo2.png' %}" alt="For-Creator-logo2"></a>
            </div>
            <div class="menu-sidebar__content js-scrollbar1">
                <nav class="navbar-sidebar">
                    <ul class="list-unstyled navbar__list">
                        <li class="active has-sub">
                            <a class="js-arrow" href="{% url 'blog:member_blog_setting' user.get_username %}">
                                <i class="fas fa-home"></i>홈</a>
                        </li>
                        <li>
                            <a href="{% url 'blog:member_blog_setting_post' user.get_username %}">
                                <i class="fas fa-pencil-square-o"></i>글</a>
                        </li>
                        <li>
                            <a href="{% url 'blog:member_blog_setting_category' user.get_username %}">
                                <i class="fas fa-archive"></i>카테고리</a>
                        </li>
                        <li>
                            <a href="{% url 'blog:member_blog_setting_tag' user.get_username %}">
                                <i class="fas fa-tag"></i>태그</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>
        <!-- END MENU SIDEBAR-->

        <!-- PAGE CONTAINER-->
        <div class="page-container">
            <!-- HEADER DESKTOP-->
            <header class="header-desktop">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="header-wrap row justify-content-end">
                            <div class="header-button">
                                <div class="account-wrap">
                                    <div class="account-item clearfix js-item-menu">
                                        <div class="image">
                                            <img src="{% static 'cooladmin/images/icon/blank-avatar.png' %}" alt="사용자" />
                                        </div>
                                        <div class="content">
                                            <a class="{% static 'cooladmin/js-acc-btn" href="#">{{user}}</a>
                                        </div>
                                        <div class="account-dropdown js-dropdown">
                                            <div class="info clearfix">
                                                <div class="image">
                                                    <a href="#">
                                                        <img src="{% static 'cooladmin/images/icon/blank-avatar.png' %}" alt="사용자" />
                                                    </a>
                                                </div>
                                                <div class="content">
                                                    <h5 class="name">
                                                        <a href="#">{{user}}</a>
                                                    </h5>
                                                    {% if user.get_email %}
                                                    <span class="email">{{user.get_email}}</span>
                                                    {% endif %}
                                                </div>
                                            </div>
                                            <div class="account-dropdown__body">
                                                <div class="account-dropdown__item">
                                                    <a href="{% url 'blog:member_blog_setting_user' user.username %}">
                                                        <i class="zmdi zmdi-account"></i>사용자 설정</a>
                                                </div>
                                            </div>
                                            <div class="account-dropdown__footer">
                                                <a href="{% url 'logout' %}">
                                                    <i class="zmdi zmdi-power"></i>로그아웃</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- HEADER DESKTOP-->

            <!-- MAIN CONTENT-->
            {% block content %}

            {% endblock %}
            <!-- END MAIN CONTENT-->
            <!-- END PAGE CONTAINER-->

            <footer>
                <div class="row">
                    <div class="col-md-12">
                        <div class="copyright">
                            <p>
                                Copyright &copy;<script>document.write(new Date().getFullYear());</script> For-Creator All rights reserved | Template by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                            </p>
                        </div>
                    </div>
                </div>
            </footer>
        </div>

    </div>

    <!-- Jquery JS-->
    <script src="{% static 'cooladmin/vendor/jquery-3.2.1.min.js' %}"></script>
    <!-- Bootstrap JS-->
    <script src="{% static 'cooladmin/vendor/bootstrap-4.1/popper.min.js' %}"></script>
    <script src="{% static 'cooladmin/vendor/bootstrap-4.1/bootstrap.min.js' %}"></script>
    <!-- Vendor JS       -->
    <script src="{% static 'cooladmin/vendor/slick/slick.min.js' %}"></script>
    <script src="{% static 'cooladmin/vendor/wow/wow.min.js' %}"></script>
    <script src="{% static 'cooladmin/vendor/animsition/animsition.min.js' %}"></script>
    <script src="{% static 'cooladmin/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js' %}"></script>
    <script src="{% static 'cooladmin/vendor/counter-up/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'cooladmin/vendor/counter-up/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'cooladmin/vendor/circle-progress/circle-progress.min.js' %}"></script>
    <script src="{% static 'cooladmin/vendor/perfect-scrollbar/perfect-scrollbar.js' %}"></script>
    <script src="{% static 'cooladmin/vendor/chartjs/Chart.bundle.min.js' %}"></script>
    <script src="{% static 'cooladmin/vendor/select2/select2.min.js' %}"></script>

    <!-- Main JS-->
    <script src="{% static 'cooladmin/js/main.js' %}"></script>

    <!-- TagEditor JS -->
    <script src="{% static 'cooladmin/tagEditor/jquery.tag-editor.min.js' %}"></script>
</body>

</html>
<!-- end document-->