api/urls.py
from django.urls import path
from .views import CategoryList, CategoryDetail, ThemePostList, PostList, PostDetail, TagDetail, TagList


app_name = 'api'

urlpatterns = [
    path('categories', CategoryList.as_view()),
    path('categories/<int:pk>', CategoryDetail.as_view()),
    path('themes/<str:theme_slug_name>/posts', ThemePostList.as_view()),
    path('posts', PostList.as_view()),
    path('posts/<int:pk>', PostDetail.as_view()),
    path('tags', TagList.as_view()),
    path('tags/<int:pk>', TagDetail.as_view()),
]

blog/urls.py
from django.urls import register_converter, path
from .views import BlogCreateView, MemberBlogPostDetailView,  MemberBlogView, upload
from .views import MemberBlogSettingView, MemberBlogSettingPostCreateView, MemberBlogSettingPostListView, MemberBlogSettingPostEditView
from .views import MemberBlogSettingCategoryListView, MemberBlogSettingTagListView, MemberBlogSettingUserView
from . import converters

app_name = 'blog'

# url 한글 slug 문제 해결
register_converter(converters.UnicodeSlugConverter, 'uslug')

urlpatterns = [
    path('add', BlogCreateView.as_view(), name='add'),
    path('upload', upload, name='upload'),
    path('<str:username>/settings/categories', MemberBlogSettingCategoryListView.as_view(), name='member_blog_setting_category'),
    path('<str:username>/settings/posts/<int:pk>', MemberBlogSettingPostEditView.as_view(), name='member_blog_setting_post_edit'),
    path('<str:username>/settings/posts/new', MemberBlogSettingPostCreateView.as_view(), name='member_blog_setting_post_new'),
    path('<str:username>/settings/posts', MemberBlogSettingPostListView.as_view(), name='member_blog_setting_post'),
    path('<str:username>/settings/tags', MemberBlogSettingTagListView.as_view(), name='member_blog_setting_tag'),
    path('<str:username>/settings/user', MemberBlogSettingUserView.as_view(), name='member_blog_setting_user'),
    path('<str:username>/settings', MemberBlogSettingView.as_view(), name='member_blog_setting'),
    path('<str:username>/<uslug:slug_title>', MemberBlogPostDetailView.as_view(), name='member_blog_post_detail'),
    path('<str:username>', MemberBlogView.as_view(), name='member_blog'),
]

config/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from blog.views import BlogView
from .views import IndexView, JoinView

urlpatterns = [
    path('admin', admin.site.urls),
    path('api/', include('api.urls')),
    path('blog', BlogView.as_view(), name='blog_index'),
    path('blog/', include('blog.urls')),
    path('join', JoinView.as_view(), name='join'),
    path('login', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('password-reset', auth_views.PasswordResetView.as_view(template_name='password_reset.html', subject_template_name='password_reset_subject.txt', email_template_name='password_reset_email.html'), name='password_reset'),
    path('password-reset-complete', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-done', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('', IndexView.as_view(), name='index'),
]

blog/models.py
from django.db import models

#https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#referencing-the-user-model
from django.conf import settings


class Theme(models.Model):
    name = models.CharField(max_length=30, unique=True)
    slug_name = models.SlugField(max_length=50, unique=True, allow_unicode=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Blog(models.Model):
    name = models.CharField(max_length=50, unique=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    theme = models.ForeignKey(Theme, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=30)
    slug_name = models.SlugField(max_length=50, unique=True, allow_unicode=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

class Attachment(models.Model):
    name = models.CharField(max_length=30)
    image = models.ImageField(upload_to='blog/%Y/%m/%d')
    created_date = models.DateTimeField(auto_now_add=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=30)
    slug_name = models.SlugField(max_length=50, unique=True, allow_unicode=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    content = models.TextField()
    thumbnail = models.ImageField(upload_to='blog/%Y/%m/%d', blank=True) #upload path 문자열이 저장됨.
    slug_title = models.SlugField(max_length=150, unique=True, allow_unicode=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    tag = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from .models import Attachment, Blog, Category, Post, Tag


class BlogCreateForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['name', 'theme']

class MemberBlogSettingPostCreateAndEditForm(forms.ModelForm):
    form_tags = {'title': '제목', 'thumbnail': '썸네일', 'category': '카테고리', 'tag': '태그', 'content': '내용'}
    tag = forms.CharField(max_length=100, required=False)
    content = forms.CharField(widget=forms.Textarea, required=False)

    class Meta:
        model = Post
        fields = ['title', 'thumbnail', 'category', 'tag', 'content']
    
    def __init__(self, blog, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for key, value in self.form_tags.items():
            self.fields[key].label = value
            self.fields[key].widget.attrs.update({'class': 'form-control'})

            if key == 'category':
                self.fields[key].queryset = Category.objects.filter(blog=blog)
            elif key == 'tag':
                self.fields[key].widget.attrs.update({'data-role': 'tagsinput'})

class UploadImageFileForm(forms.Form):
    image = forms.ImageField()

class CustomPasswordChangeForm(PasswordChangeForm):
    form_tags = {'old_password': '이전 비밀번호', 'new_password1': '새 비밀번호', 'new_password2': '새 비밀번호 확인'}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for key, value in self.form_tags.items():
            self.fields[key].label = value
            self.fields[key].widget.attrs.update({'class': 'form-control'})

blog/views.py
import uuid
from django.views import View
from django.views.generic import CreateView, DetailView, ListView, TemplateView, UpdateView
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Group, User
from django.contrib.auth.decorators import login_required, permission_required
from django.db import transaction
from django.db.models import Count, Q
from django.http import HttpResponse, Http404, JsonResponse
from django.utils.text import slugify
from .models import Attachment, Blog, Category, Theme, Post, Tag
from .forms import BlogCreateForm, CustomPasswordChangeForm, MemberBlogSettingPostCreateAndEditForm, UploadImageFileForm


class BlogView(ListView):
    model = Post
    paginate_by = 6
    template_name = 'blog/blog.html'

    def get_queryset(self):
        search_type = self.request.GET.get('search-type', '')
        value = self.request.GET.get('value', '')

        if search_type and value:
            if search_type == 'question':
                return Post.objects.filter(Q(title__icontains=value) | Q(content__icontains=value) | Q(blog__name__icontains=value) | Q(user__username__icontains=value)).order_by('-id')

        return Post.objects.none()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['theme_list'] = Theme.objects.all()
        search_type = self.request.GET.get('search-type', '')
        value = self.request.GET.get('value', '')

        if search_type and value:
            context['search_type'] = search_type
            context['value'] = value

        return context

class BlogCreateView(LoginRequiredMixin, PermissionRequiredMixin, View):
    form_class = BlogCreateForm
    login_url = '/login'
    permission_required = 'blog.add_blog'
    redirect_field_name = '/login'
    success_url = '/blog'

    def get(self, request, *args, **kwargs):
        return HttpResponse(status=404)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            with transaction.atomic():
                request_user = self.request.user
                new_blog = form.save(commit=False)
                new_blog.user = request_user
                new_blog.save()
                
                blogger_group = Group.objects.get(name='Blogger')
                blogger_group.user_set.add(request_user)
                
                member_group = Group.objects.get(name='Member')
                request_user.groups.remove(member_group)
                
                messages.success(self.request, '<strong>블로그 만들기에 성공했습니다!</strong> 이제 당신은 블로거가 되었습니다.')
        else:
            error_data = form.errors.get_json_data()
            
            if 'name' in error_data and error_data['name'][0]['code'] == 'unique':
                messages.error(self.request, '<strong>같은 이름의 블로그가 이미 존재합니다.</strong> 블로그 이름을 다른 이름으로 지으세요.')
        
        return redirect(self.success_url)

class MemberBlogView(ListView):
    model = Post
    paginate_by = 6
    template_name = 'blog/member_blog.html'

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs['username'])
        search_type = self.request.GET.get('search-type', '')
        value = self.request.GET.get('value', '')

        if search_type and value:
            if search_type == 'question':
                return Post.objects.filter(Q(title__icontains=value) | Q(content__icontains=value), user=user).order_by('-id')
            elif search_type == 'category':
                if value == 'etc':
                    return Post.objects.filter(user=user, category__isnull=True).order_by('-id')
                    
                return Post.objects.filter(user=user, category__slug_name=value).order_by('-id')
            elif search_type == 'tag':
                return Post.objects.filter(user=user, tag__slug_name=value).order_by('-id')

        return Post.objects.filter(user=user).order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = get_object_or_404(User, username=self.kwargs['username'])
        blog =  get_object_or_404(Blog, user=user)
        context['blog'] = blog
        context['categories'] = Category.objects.filter(blog=blog).annotate(Count('post'))
        context['category_etc_count'] = Post.objects.filter(blog=blog, category__isnull=True).count()
        context['tags'] = Tag.objects.filter(blog=blog)

        search_type = self.request.GET.get('search-type', '')
        value = self.request.GET.get('value', '')

        if search_type and value:
            context['search_type'] = search_type
            context['value'] = value

        return context

class MemberBlogPostDetailView(DetailView):
    model = Post
    slug_field = 'slug_title'
    slug_url_kwarg = 'slug_title'
    template_name = 'blog/member_blog_post_detail.html'

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs['username'])
        
        return Post.objects.filter(user=user)
        
class MemberBlogSettingView(TemplateView):
    template_name = 'blog/member_blog_setting.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        blog = get_owner_blog(self)
        context['blog'] = blog
        
        categories = Category.objects.filter(blog=blog).annotate(Count('post'))
        dict_categories = {}

        for category in categories:
            dict_categories[category.name] = str(category.post__count)

        context['categories'] = dict_categories
        
        return context

class MemberBlogSettingPostListView(ListView):
    model = Post
    paginate_by = 4
    template_name = 'blog/member_blog_setting_post.html'

    def get_queryset(self):
        blog = get_owner_blog(self)
        search_type = self.request.GET.get('search-type', '')
        value = self.request.GET.get('value', '')

        if search_type and value:
            if search_type == 'question':
                return Post.objects.filter(Q(title__icontains=value) | Q(content__icontains=value), blog=blog).order_by('-id')

        return Post.objects.filter(blog=blog).order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_type = self.request.GET.get('search-type', '')
        value = self.request.GET.get('value', '')

        if search_type and value:
            context['search_type'] = search_type
            context['value'] = value
    
        return context

class MemberBlogSettingPostCreateView(CreateView):
    template_name = 'blog/member_blog_setting_post_new.html'

    def get(self, request, *args, **kwargs):
        context = {'form': MemberBlogSettingPostCreateAndEditForm(get_owner_blog(self))}

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        blog = get_owner_blog(self)
        form = MemberBlogSettingPostCreateAndEditForm(blog, request.POST, request.FILES)

        if form.is_valid():
            with transaction.atomic():
                new_tags = get_new_tags(self, form.cleaned_data['tag'])
                form.cleaned_data['tag'] = new_tags

                new_post = form.save(commit=False)
                new_post.slug_title = get_permalink(new_post.title)
                new_post.blog = blog
                new_post.user = request.user

                if new_post.thumbnail:
                    new_post.thumbnail.name = get_extension_permalink(new_post.thumbnail.name)

                new_post.save()
                form.save_m2m()

                messages.success(request, '글을 생성했습니다.')

            return redirect('blog:member_blog_setting_post', request.user)
        else:
            form = MemberBlogSettingPostCreateAndEditForm(blog)
        
        return render(request, self.template_name, {'form': form})

class MemberBlogSettingPostEditView(UpdateView):
    template_name = 'blog/member_blog_setting_post_edit.html'

    def get(self, request, *args, **kwargs):
        post = Post.objects.get(id=self.kwargs['pk'])
        tags = [tag.name for tag in list(post.tag.all())]
        tag_text = ','.join(tags)

        initial_data = {'title': post.title, 'thumbnail':  post.thumbnail, 'category': post.category, 'tag':  tag_text, 'content': post.content}
        context = {'form': MemberBlogSettingPostCreateAndEditForm(get_owner_blog(self), initial=initial_data)}

        print(context)

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        blog = get_owner_blog(self)
        form = MemberBlogSettingPostCreateAndEditForm(blog, request.POST, request.FILES)

        if form.is_valid():
            with transaction.atomic():
                post = Post.objects.get(id=self.kwargs['pk'])
                form_tag = get_new_tags(self, form.cleaned_data['tag'])
                form_title = form.cleaned_data['title']

                post.thumbnail = form.cleaned_data['thumbnail']
                post.category = form.cleaned_data['category']
                post.content = form.cleaned_data['content']

                if post.title is not form_title:
                    post.title = form_title
                    post.slug_title = get_permalink(post.title)
                
                post.tag.set(form_tag)
                post.save()

                messages.success(request, '글을 수정했습니다.')

            return redirect('blog:member_blog_setting_post', request.user)
        else:
            form = MemberBlogSettingPostCreateAndEditForm(blog)
        
        return render(request, self.template_name, {'form': form})

blog/templates/blog/blog.html
{% extends 'blog_base.html' %}

{% block title %}블로그 홈{% endblock %}

{% load static %}

{% block content %}

<!--Main layout-->
<main class="pt-4">

    <!--Blog section-->
    <section>
        <div class="container">

            <!--Section heading-->
            <h2 class="text-center h2 my-5 pt-4">For-Creator</h2>
            <!--Section description-->
            <p class="text-center dark-grey-text w-responsive mx-auto mb-5">
                크리에이터들이 만든 세계를 감상하세요.
            </p>

    {% if messages %}
        {% for message in messages %}
            <div class="row justify-content-center">
            {% if message.tags == 'error' %}
                <div class="alert alert-danger alert-dismissible" role="alert">
            {% else %}
                <div class="alert alert-{{message.tags}} alert-dismissible" role="alert">
            {% endif %}
                    {{message|safe}}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
        {% endfor %}
    {% endif %}
            
            <!-- Search form -->
            <form class="form-inline d-flex justify-content-center md-form form-sm">
                <input type="hidden" name="search-type" value="question">
                <input class="form-control form-control-sm mr-3 w-75" type="text" name="value" placeholder="검색어를 입력해주세요" aria-label="Search">
                <i class="fas fa-search" aria-hidden="true"></i>
            </form>

            {% if post_list %}
            <!--Grid row-->
            <div class="row text-center mb-2">
                {% for post in page_obj %}

                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">
                    <!--Featured image-->
                    <div class="view overlay z-depth-1 mb-2">
                    {% if post.thumbnail %}
                        <img src="{{post.thumbnail.url}}" class="img-fluid" alt="blog thumbnail">
                    {% else %}
                        <img src="{% static 'img/blog/blog-post-img1.jpg' %}" class="img-fluid" alt="blog thumbnail">
                    {% endif %}
                        <a href="{% url 'blog:member_blog_post_detail' username=post.user slug_title=post.slug_title%}">
                            <div class="mask rgba-white-slight"></div>
                        </a>
                    </div>

                    <h4 class="mb-2 mt-4 font-weight-bold">
                        <a href="{% url 'blog:member_blog_post_detail' username=post.user slug_title=post.slug_title%}">{{post.title}}</a>
                    </h4>

                    <!--Grid row-->
                    <div class="row">

                        <!--Grid column-->
                        <div class="col-lg-6 col-md-6 text-lg-left">
                            <p class="grey-text">
                                <i class="far fa-user" aria-hidden="true"></i><a href="{% url 'blog:member_blog' post.user %}"> {{post.user}}</a>
                            </p>
                        </div>
                        <!--Grid column-->
                        
                        <!--Grid column-->
                        <div class="col-lg-6 col-md-6 text-lg-right">
                            <p class="grey-text">
                                <i class="far fa-calendar" aria-hidden="true"></i> {{post.created_date|date:'Y-m-d H:i'}}
                            </p>
                        </div>
                        <!--Grid column-->

                    </div>
                    <!--Grid row-->

                    <p class="dark-grey-text">{{ post.content|striptags }}</p>
                    <a href="{% url 'blog:member_blog_post_detail' username=post.user slug_title=post.slug_title%}" class="btn custom-color-gradient btn-rounded btn-sm">
                        Read more
                    </a>
                    <hr class="mt-1" style="max-width: 90px">
                </div>
                <!--Grid column-->
                {% endfor %}

            </div>
            <!--Grid row-->

             <!--Pagination -->
             <nav class="my-4 flex-center">
                <ul class="pagination mb-0">

                    {% if page_obj.has_previous %}
                    <!--Arrow left-->
                    <li class="page-item active">
                        <a href="?search-type={{search_type}}&value={{value}}&page={{page_obj.previous_page_number}}" class="custom-color page-link" aria-label="Previous">
                            이전 페이지
                        </a>
                    </li>
                    {% endif %}

                    {% if page_obj.has_next %}
                    <!--Arrow right-->
                    <li class="page-item active">
                        <a href="?search-type={{search_type}}&value={{value}}&page={{page_obj.next_page_number}}" class="custom-color page-link" aria-label="Next">
                            다음 페이지
                        </a>
                    </li>
                    {% endif %}

                </ul>
            </nav>
            <!--/Pagination -->

            {% else %}
                <ul class="nav nav-tabs md-tabs" id="themeTab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="전체-tab" data-toggle="tab" href="#전체" role="tab" aria-controls="전체-tab" aria-selected="true">전체</a>
                    </li>
                {% for theme in theme_list %}
                    <li class="nav-item">
                        <a class="nav-link" id="{{theme.slug_name}}-tab" data-toggle="tab" href="#{{theme.slug_name}}" role="tab" aria-controls="{{theme.slug_name}}-tab" aria-selected="false">
                            {{theme}}
                        </a>
                    </li>
                {% endfor %}
                </ul>
                <div class="tab-content card pt-5" id="themeTabContent">
                    <div class="tab-pane fade show active" id="전체" role="tabpanel" aria-labelledby="전체-tab">
                        <p>Raw denim qui.</p>
                    </div>
                {% for theme in theme_list %}
                    <div class="tab-pane fade" id="{{theme.slug_name}}" role="tabpanel" aria-labelledby="{{theme.slug_name}}-tab">
                        <p>Food truck fixie locavore, acc</p>
                    </div>
                {% endfor %}
                </div>
            {% endif %}
        </div>

    </section>
    <!--Blog section-->

</main>
<!--Main layout-->

<!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<script>
function getActiveTheme() {
    return $('#themeTab li a.active').attr('href');
}

var theme = getActiveTheme();

// Initial Page Load
if (theme === "#전체") {
    $.get('/api/posts')
    .done(function (data) {
        createTabContent(data, theme);
    });
}
</script>
<script>
$('#themeTab a').click(function (e) {
    e.preventDefault();
    $(this).tab('show');

    var theme = $(this).attr('href');
    var requestUrl = (theme !== '#전체') ? '/api/themes/' + theme.slice(1) + '/posts' : '/api/posts';

    $.get(requestUrl)
    .done(function (data) {
        createTabContent(data, theme);
    });
});
</script>
<script>
// 동적으로 만들어진 Element는 $(document).on(...)으로 접근
$(document).on('click', '.pagination li a[href="#"]', function (e) {
    e.preventDefault();
    var page = $(this).attr('data-page');

    $.get(page)
    .done(function (data) {
        var theme = getActiveTheme();
        
        var tabContent = createTabContent(data, theme);
        tabContent.children('div.row.text-center.mb-2').hide();
        tabContent.children('div.row.text-center.mb-2').fadeIn(1000);
    });

    $('html').scrollTop(0);
});
</script>
<script>
function createPosts(data) {
    var div = $('<div class="row text-center mb-2"></div>');
    var posts = ''

    $.each(data.results, function(index, item) {
        var createdDate = '<div class="col-lg-6 col-md-6 text-lg-right"><p class="grey-text"><i class="far fa-calendar" aria-hidden="true"></i> ' + item.created_date + '</p></div>';
        var user = '<div class="col-lg-6 col-md-6 text-lg-left"><p class="grey-text"><i class="far fa-user" aria-hidden="true"></i><a href="/blog/' + item.user + '"> ' + item.user + '</a></p></div>';
        var postMeta = $('<div class="row"></div>').html(user + createdDate);
        var thumbnail = '';

        var postUrl = '/blog/' + item.user + '/' + item.slug_title;

        if (item.thumbnail) {
            thumbnail += '<div class="view overlay z-depth-1 mb-2"><img src="' + item.thumbnail+ '" class="img-fluid" alt="blog image"><a href="' + postUrl + '"><div class="mask rgba-white-slight"></div></a></div>';
        } else {
            var defaultThumbnail = "{% static  'img/blog/blog-post-img1.jpg' %}";
            thumbnail += '<div class="view overlay z-depth-1 mb-2"><img src="' + defaultThumbnail + '" class="img-fluid" alt="blog thumbnail"><a href="' + postUrl + '"><div class="mask rgba-white-slight"></div></a></div>';
        }
        
        var title = '<h4 class="mb-2 mt-4 font-weight-bold"><a href="' + postUrl + '">' + item.title +'</a></h4>';
        var contentStripTags = item.content.replace(/(<([^>]+)>)/ig,"");
        var content = '<p class="dark-grey-text" class="btn custom-color-gradient btn-rounded btn-sm">' + contentStripTags  + '</p>';
        var readMore = '<a href="' + postUrl + '" class="btn custom-color-gradient btn-rounded btn-sm">Read more</a>';
        var hr = '<hr class="mt-1" style="max-width: 90px">'

        var post = $('<div class="col-lg-4 col-md-12 mb-4"></div>').html(thumbnail + title + postMeta.prop('outerHTML') + content + readMore + hr);

        posts += post.prop('outerHTML');
    });

    var result = div.html(posts).prop('outerHTML');

    return result
}

function createPaginationButton (data) {
    result = ''
        
    if (data.previous) {
        const previousPage = new URL(data.previous);

        result +=  '<li class="page-item active"><a href="#" data-page="' + previousPage.pathname + previousPage.search + '" class="page-link" aria-label="Previous">이전 페이지</a></li>'
    }
    
    if (data.next) {
        const nextPage = new URL(data.next);

        result +=  '<li class="page-item active"><a href="#" data-page="' + nextPage.pathname + nextPage.search + '" class="page-link" aria-label="Previous">다음 페이지</a></li>'
    }
        
    return result
}

function createPagination (data) {
    var nav = $('<nav class="my-4 flex-center"></nav>');
    var ul = $('<ul class="pagination mb-0"></ul>');
    var paginationButton = createPaginationButton(data);

    var result = nav.html(ul.html(paginationButton).prop('outerHTML')).prop('outerHTML');

    return result
}

function createTabContent(data, theme) {
    var posts = createPosts(data);
    var result = $(theme).html(posts + createPagination(data));

    return result
}
</script>
{% endblock %}

blog/templates/blog/member_blog_setting.html
{% extends 'member_blog_setting_base.html' %}

{% load static %}

{% block content %}
<div class="main-content">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="overview-wrap">
                        <h2 class="title-1">블로그 설정 홈</h2>
                    </div>
                </div>
            </div>
            <br>
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <div class="au-card chart-percent-card">
                        <div class="au-card-inner">
                            <h3 class="title-2 tm-b-5">카테고리 점유율<small>(전체 글 중에서 해당 카테고리 글의 비율)</small></h3>
                            <div class="row no-gutters">
                                <div class="col-xl-12">
                                    <div class="percent-chart">
                                        <canvas id="category-chart"></canvas>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Jquery JS-->
<script src="{% static 'cooladmin/vendor/jquery-3.2.1.min.js' %}"></script>

<!-- Vendor JS       -->
<script src="{% static 'cooladmin/vendor/chartjs/Chart.bundle.min.js' %}"></script>

{{categories|json_script:"categories"}}

<script>
function getRandomColor() {
    var letters = '0123456789ABCDEF'.split('');
    var color = '#';
    for (var i = 0; i < 6; i++) {
        color += letters[Math.floor(Math.random() * 16)];
    }
    
    return color;
}
</script>
<script>
var categories = JSON.parse($('#categories').text());

var categoryLabels = [];
var categoryData = [];
var categoryBackgroundColors = [];

$.each(categories, function(key, value) {
    categoryLabels.push(key);
    categoryData.push(Number(value));
    categoryBackgroundColors.push(getRandomColor());
});

var ctx = 'category-chart';

var chart = new Chart(ctx, {
    type: 'doughnut',
    data: {
        labels: categoryLabels,
        datasets: [{
            data: categoryData,
            backgroundColor: categoryBackgroundColors
        }]
    },
    options : {
            legend: {
                position: 'left'
            }
        }
});
</script>
{% endblock %}